name: null
favicon: null
layout_spectrum: 1
typography_spectrum: 0.59485
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eaeaea'
    - '#bcb4ad'
    - '#8295c4'
    - '#66524c'
    - '#181f16'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose: []
