name: null
favicon: null
layout_spectrum: 1
typography_spectrum: 0.99996
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#feffff'
    - '#d0d0d0'
    - '#a1988e'
    - '#0c0c0e'
    - '#6c5644'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose: []
