name: null
favicon: null
layout_spectrum: 0.16502
typography_spectrum: 0.99996
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9c8f99'
    - '#ffe9ad'
    - '#cfbcc0'
    - '#695c65'
    - '#040301'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose: []
