name: null
favicon: null
layout_spectrum: 0.02289
typography_spectrum: 0.00003
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bf0a30'
    - '#ffffff'
    - '#002868'
    - '#d04a67'
    - '#5a527e'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose: []
