name: null
favicon: null
layout_spectrum: 0.36577
typography_spectrum: 0.37446
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#beb4ae'
    - '#271d1e'
    - '#ff0036'
    - '#ff41bb'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose: []
