name: Wes
favicon: null
layout_spectrum: 0.50051
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0b0b'
    - '#4c4c54'
    - '#807876'
    - '#c6ad84'
    - '#bd6a1c'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
