name: Wes
favicon: null
layout_spectrum: 0.68057
typography_spectrum: 0.90816
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060004'
    - '#d28653'
    - '#b16b3f'
    - '#80391e'
    - '#541f14'
  brandStrength: 0
  lightness: 0.625
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
